version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/mini-4th-frontend

permissions:
  - object: /var/www/mini-4th-frontend
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300