version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

permissions:
  - object: /home/ubuntu/app
    pattern: '**'
    mode: '0755'
    owner: ubuntu
    group: ubuntu
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300