version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mini-4th-frontend

permissions:
  - object: /home/ec2-user/mini-4th-frontend
    pattern: '**'
    mode: '0755'
    owner: ec2-user
    group: ec2-user
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300