version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
        - echo "=== NODE CHECK ==="
        - node -v
        - npm -v
        - npm ci
    commands:
      - echo "Install dependencies"
      - npm install

  build:
    commands:
      - echo "Build Next.js"
      - npm run build

artifacts:
  files:
    - ".next/**/*"
    - "public/**/*"

    - "package.json"
    - "next.config.*"

    - "appspec.yml"
    - "deploy-scripts/**/*"