version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install dependencies"
      - npm install

  build:
    commands:
      - echo "Build Next.js"
      - npx next build

artifacts:
  files:
    - ".next/**/*"
    - "public/**/*"

    - "package.json"
    - "next.config.*"

    - "deploy-scripts/**/*"